### ISSUE TITLE
Naming collision

### ISSUE THREAD

**Issue by pbaranay** [GlenHughes/react-native-countdown-clock#1]
Hi there!

I should preface this with saying that I am brand new to React Native (and using `npm` as a package manager).

I have the basic React Native app (the one you get when you run `react-native init FooBar`), and I wanted to add your countdown clock to it. I ran `npm install react-native-countdown-clock --save`, and added the `import` statement and `CountdownTimer` tag to my `index.ios.js`. However, I began getting errors from `npm` about naming collisions.

Besides the countdown clock, my other dependencies are:

```
    "react": "~15.4.1",
    "react-native": "0.42.0"
```

And here is the error when running `npm start`:

```
jest-haste-map: @providesModule naming collision:
  Duplicate module name: react-native
  Paths: /Users/pbaranay/Desktop/Timer/react/DraftTimer/node_modules/react-native/package.json collides with /Users/pbaranay/Desktop/Timer/react/DraftTimer/node_modules/react-native-countdown-clock/node_modules/react-native/package.json

This warning is caused by a @providesModule declaration with the same name across two different files.
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: react-native-vector-icons
  Paths: /Users/pbaranay/Desktop/Timer/react/DraftTimer/node_modules/react-native/local-cli/core/__fixtures__/files/package.json collides with /Users/pbaranay/Desktop/Timer/react/DraftTimer/node_modules/react-native-countdown-clock/node_modules/react-native/local-cli/core/__fixtures__/files/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
  Duplicate module name: react-native-vector-icons
  Paths: /Users/pbaranay/Desktop/Timer/react/DraftTimer/node_modules/react-native/local-cli/core/__fixtures__/files/package.json collides with /Users/pbaranay/Desktop/Timer/react/DraftTimer/node_modules/react-native-countdown-clock/node_modules/react-native/local-cli/core/__fixtures__/files/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
    at HasteMap._updateHasteMap (/Users/pbaranay/Desktop/Timer/react/DraftTimer/node_modules/react-native/packager/src/node-haste/DependencyGraph/HasteMap.js:158:13)
    at p.getName.then.name (/Users/pbaranay/Desktop/Timer/react/DraftTimer/node_modules/react-native/packager/src/node-haste/DependencyGraph/HasteMap.js:133:31)
```

I hope this is enough information to help you reproduce, or help me fix whatever error I've caused myself ;)

**Comment by GlenHughes** [comment]
Hi,

I have now fixed this issue and merged into master.

Let me know if you have any more problems.

Thanks
